from __future__ import annotations

from typing import Protocol
from uuid import UUID

from ai_orchestrator.domain.models.artifact import Artifact
from ai_orchestrator.domain.models.approval import ApprovalGate
from ai_orchestrator.domain.models.task import Task
from ai_orchestrator.domain.models.workflow import Workflow
from ai_orchestrator.domain.models.execution import ExecutionEvent


class WorkflowRepository(Protocol):
    async def add(self, workflow: Workflow) -> None: ...

    async def get(self, workflow_id: UUID) -> Workflow: ...

    async def update(self, workflow: Workflow) -> None: ...

    async def list_recent(self, limit: int = 50) -> list[Workflow]: ...


class TaskRepository(Protocol):
    async def add_many(self, tasks: list[Task]) -> None: ...

    async def add(self, task: Task) -> None: ...

    async def get(self, task_id: UUID) -> Task: ...

    async def claim_queued(self, task_id: UUID) -> Task | None: ...

    async def update(self, task: Task) -> None: ...

    async def list_by_workflow(self, workflow_id: UUID) -> list[Task]: ...


class ArtifactRepository(Protocol):
    async def add(self, artifact: Artifact) -> None: ...

    async def list_by_task(self, task_id: UUID) -> list[Artifact]: ...

    async def list_by_workflow(self, workflow_id: UUID) -> list[Artifact]: ...


class ApprovalRepository(Protocol):
    async def add(self, gate: ApprovalGate) -> None: ...

    async def get(self, gate_id: UUID) -> ApprovalGate: ...

    async def update(self, gate: ApprovalGate) -> None: ...

    async def list_by_workflow(self, workflow_id: UUID) -> list[ApprovalGate]: ...


class ExecutionEventRepository(Protocol):
    async def add(self, event: ExecutionEvent) -> None: ...

    async def list_by_workflow(self, workflow_id: UUID) -> list[ExecutionEvent]: ...
